{% set name = "rubin-scheduler" %}
{% set version = "3.9.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dac40c11a04e38b53e00ca2295d42f9c23f9466917367df66af8df01338d3126

build:
  entry_points:
    - scheduler_download_data = rubin_scheduler.data.scheduler_download_data:scheduler_download_data
    - rs_download_sky = rubin_scheduler.data.rs_download_sky:rs_download_sky
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - healpy
    - pandas
    - numexpr
    - scipy
    - astroplan
    - astropy-base
    - pytables
    - h5py
    - requests
    - shapely
    - tqdm

test:
  imports:
    - rubin_scheduler
  commands:
    - scheduler_download_data --help
    - rs_download_sky --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lsst/rubin_scheduler
  summary: Scheduling algorithms for Vera C. Rubin Observatory's Legacy Survey of Space and Time (LSST).
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roceb
    - rhiannonlynne
